class PersonData {
  static const List<String> names = [
    'Elon Musk',
    'Jeff Bezos',
    'Bill Gates',
    'Warren Buffett',
    'Mark Zuckerberg',
    'Tim Cook',
    'Sundar Pichai',
    'Larry Page',
    'Sergey Brin',
    'Jack Ma',
    'Larry Ellison',
    'Richard Branson',
    'MacKenzie Scott',
    'Mukesh Ambani',
    'Michael Bloomberg',
    'Xi Jinping',
    'Vladimir Putin',
    'Joe Biden',
    'Angela Merkel',
    'Emmanuel Macron',
    'Justin Trudeau',
    'Mohammed bin Salman',
    'Narendra Modi',
    'Boris Johnson',
    'Kamala Harris',
    'Kim Jong Un',
    'António Guterres',
    'Christine Lagarde',
    'Pope Francis',
    'Melinda French Gates',
    'Sheryl Sandberg',
    'Oprah Winfrey',
    'Rihanna',
    'Tyler Perry',
    'Kylie Jenner',
    'Kim Kardashian',
    'Beyoncé',
    'Jay-Z',
    'Tim Berners-Lee',
    'Shinzo Abe',
    'Barack Obama',
    'Michelle Obama',
    'George Clooney',
    'Brad Pitt',
    'Leonardo DiCaprio',
    'Cristiano Ronaldo',
    'Lionel Messi',
    'Serena Williams',
    'Roger Federer'
  ];
}
